[kubernetes]
disabled = true
format = '[$symbol$context( \(ğŸŒŒ-$namespace\))]($style) in '

[git_branch]
symbol = "ğŸŒ± "

[aws]
disabled = true

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
